<?php
function nouvelle_page_menu() {
     $items = array();
     $items['formulaire_faq'] = array(
        'title'             =>  'Page inscription',  //page title
        'description'       =>  'new_page Information',  //description show when mouse hover on link
      //  'type' => MENU_NORMAL_ITEM, // add in the custom menu like a link
        'page callback'     =>  'page_creation_1',  //callback function which is invoked when menu item is called.
        'access callback'   =>  true,  //any user can access this page
       );
      return $items;
}

/*
* implement hook_theme()
*/
function nouvelle_page_theme() {
        $themes = array();
        $themes['mynew_custompage'] = array(
        'variables' => array(),
        'template' => 'templates/mynew_custompage',
        'path' => drupal_get_path('module', 'nouvelle_page'),
      );
     return $themes;
}

/*
* implement page callback()
*/
function page_creation_1() {
  return theme('mynew_custompage');
}
